### ISSUE TITLE
ammo box

### ISSUE THREAD

**Issue by zuckung** [thewierdnut/endless-mobile#111]
### Problem Description

Can we please get the ammo  box back?

### Related Issue Links

https://github.com/thewierdnut/endless-mobile/issues/94

### Desired Solution

box "ammo"
		from -170 330 top right
		to -80 -120 bottom right

Would be nice.
it's over the deploy button, which is over the secondary fire button. 2nd button column from right.
Expanding upwards would let enough space for the fuel ui element.

### Alternative Approaches

Or maybe 1 button width more to the left? For smaller displays?

**Comment by YiffLord** [comment]
Now that there is a button expansion plugin, couldn't the ammo counter be invisible in the base apk but still exist in the code, so that the plugins that may modify it can do so?

If this is more complex / effort requiring than just putting it back then don't even consider it, why do extra stuff to get the same result...

Edit: Now that I checked Hecter94's archive, there are some plugins that modify the game's UI, by setting a new one or moving elements of the original.

**Comment by thewierdnut** [comment]
If the "Show buttons on map" preference is on, now you can specify the ammo box from the `"main buttons"` interface instead of the hud. Something like this should work:

```
interface "main buttons"
   	... other stuff ...
   	anchor top right
	visible if "has secondary"
	active
	box "ammo"
		from -280 0 to -170 300
```

Note that the icon information will still be drawn from the hud interface.

**Comment by zuckung** [comment]
Thx
