### ISSUE TITLE
settings aren't saved

### ISSUE THREAD

**Issue by johndh** [thewierdnut/endless-mobile#13]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Settings aren't saved between sessions, and first-time help dialogues reset every time.

### Steps to Reproduce

Play the game for a little while, change some settings. Close the app. Launch the game again.

### Expected Behavior

Settings such as "rehire extra crew when lost" should carry over between sessions, and first-time help should only display the first time unless manually reset.

### Operating System

Android

### Game Source

Other (please describe)

### Game Version

0.9.16.1 from F-Droid

**Comment by thewierdnut** [comment]
Are your save games working ok? Are you closing the app using the quit button or by just navigating to a different app and letting the operating system shut it down?

**Comment by johndh** [comment]
The saves have been working fine as far as I can tell. Usually I'm just navigating away and coming back later, but sometimes I close the app with the task manager. I hadn't even noticed that there was an actual "quit" button, but using the quit button does appear to save the settings and doesn't reset the help.

Are the settings only meant to be saved upon a proper quit?

**Comment by thewierdnut** [comment]
They save on exit, but endless-sky is a c++ program, which has a distinct start and stop to its lifecycle. Android apps have a very complicated lifecycle, and can be terminated at any time. I should probably either tap into the android callbacks if SDL will let me, or modify the settings to save automatically whenever they are modified. 

Now that I think about it, there is probably a related bug where if you land on a planet, then navigate away from the game for a while, then when you reload the game from scratch, it may have reverted your pilot to the previous planet, all because the app is terminated without allowing it to go through a proper exit.

**Comment by johndh** [comment]
> Now that I think about it, there is probably a related bug where if you land on a planet, then navigate away from the game for a while, then when you reload the game from scratch, it may have reverted your pilot to the previous planet, all because the app is terminated without allowing it to go through a proper exit.

I think I've experienced this, but haven't tested it to be sure. Incidentally, I'm about 22 hours in, and so far I've been thoroughly enjoying it!

**Comment by johndh** [comment]
It appears that "main zoom factor" is sometimes not saved, even when using the quit button. I'm not sure exactly how to reproduce it.

**Comment by off-by-zero-error** [comment]
consistantly experiencing this, the entire settings page reverts, including volume, zoom, targeting, and dismissed help text.  the real bother is targeting behaviour which would badly catch me out without warning.  luckily the help texts reappearing remind me to rechange them.  what i don't know is if the user defined controls would also be lost, as i don't have an attached keyboard, i would assume so because volume appears across all preferance pages.  would it help if i confirm with an otg adapter or is it no difference?

**Comment by off-by-zero-error** [comment]
oh and yes, it jumps back a planet too, consistant with progress being saved when leaving planets. 

 my phone is still quite zealous with closing apps when they are exempt from battery saving, so this happens alot. 

 also, great game!  i appreciate there is far more depth in the story than the old space trader days.  i'm reluctant to search through issues because of spoilers! 

edited typo

**Comment by thewierdnut** [comment]
I spent some time troubleshooting the android lifecycle code as it integrates with SDL. The code looks like it is *supposed* to work, but it looks like when the android operating system tells the program to quit, SDL waits for the main thread to quit, and android doesn't like that, and it just terminates the program with SIGKILL. 

I think I'm going to opt for a simpler solution. I'll just save settings when they are modified, and auto-save when you land on a planet.

**Comment by thewierdnut** [comment]
This should  be fixed on the latest continuous build now. I'll post a new fdroid build soon.
