### ISSUE TITLE
interface scaling/scrolling

### ISSUE THREAD

**Issue by johndh** [thewierdnut/endless-mobile#14]
### Problem Description

There are some interface elements that don't fit entirely on (at least) some screens. Perhaps dialog boxes should be scrollable or scaled to the screen's available real estate? Buttons in particular get cut off.
![Screenshot_20221025-074207](https://user-images.githubusercontent.com/692397/201255680-ec29e35a-86a2-4e79-9983-3e9e530a2cba.png)
![Screenshot_20221025-073759](https://user-images.githubusercontent.com/692397/201255681-81c359a4-0fc4-47cd-af37-c1bfc1b54887.png)

### Related Issue Links

Any upstream discussion of wide screen displays?

### Desired Solution

Scrolling and/or scaling in UI elements 

### Alternative Approaches

Dialog boxes could be widened and buttons could be moved up a little.

**Comment by thewierdnut** [comment]
I have modified a few of these ui's, but they have a nasty habit of being changed upstream, and its hard to keep up with them. I usually end up just reverting my changes. 

Endless sky has a pixel-based positioning system for all of its UI elements. Since, especially for 4k screens, this can make the text so small as to be unreadable, they added a UI-scaling config as a hack. By default, the desktop leaves the scaling at the smallest value (100%). Since pixels on mobile devices tend to be at a higher dpi, the problem is even worse, so I've chosen to instead default the scaling value to as high as it will go, which leaves some of the dialogs a little cramped for space. 

There isn't much I can do about the info dialog (it has too many elements, and gets changed to frequently) other than complain upstream. I might be able to change the generic dialog (the one with the help text) since it is much simpler. In the meantime, there are two workarounds you can try. 
1. Adjust your ui scaling to a value that makes sense for your device, by adjusting the Preferences->Settings->Main zoom factor
2. If you turn on fullscreen, SDL will hide your android navigation buttons and your status bar, which will give you  a few more pixels to work with. That is in Preferences->Settings->Screen mode. I've left this off by default, because the android back button is pretty useful to have here, but you can get around without it for the most part.

**Comment by thewierdnut** [comment]
I've adjusted the popup dialog width for larger dialog text in commit 3afd4a4
