### ISSUE TITLE
Holding the jump button doesn't halt the jump

### ISSUE THREAD

**Issue by asl97** [thewierdnut/endless-mobile#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Holding the jump button doesn't stop to wait for escort before the jumps happen

### Steps to Reproduce

1. Hold the jump button
2. See it jumps as soon as the ship is ready

### Expected Behavior

Jumps only after letting go of the button

### Device type

POCO F3

### Game Version

0.9.16.1-28

### Additional Information

Holding the jump button (after mapping it in the settings) with an actual keyboard is working

<details><summary>unrelated issue</summary>There are other unrelated issue with android 12 and keyboard at the moment though  (numlock+short keyboard without numlock button)</details>

**Comment by thewierdnut** [comment]
Heh... so far my way to work around this has been to make sure my flagship has a slower turn rate than the rest of my fleet. 

This is going to be a difficult one to solve because the underlying UI button plumbing only handles single clicks, not fingerdown/fingerup events.

**Comment by johndh** [comment]
What about double clicks? Some ideas come to mind:
1. If the game recognizes some condition when your ship is preparing to jump, maybe the jump button could recognize that condition so that clicking it again will initiate a "jump when ready" command.
2. Would it be easier for the button to change after the first click, so that the first click is "jump" and a subsequent click is "jump when ready"? I don't know how the logic would work if the first jump attempt is interrupted.

Both of these seem hacky to me.

3. An upstream change to the jump command that makes hitting 'j' twice initiate "jump when ready" would entail the same for clicking the button twice.

I don't know if any of these would work with jump drives, or if your ship is already pointed in the right direction, so that the first click would be instantly carried out before you could click a second time.

**Comment by johndh** [comment]
Related:
https://github.com/endless-sky/endless-sky/pull/5686
https://github.com/endless-sky/endless-sky/issues/6264

**Comment by thewierdnut** [comment]
The jump functionality is controlled by Commands, which are polled every frame using keyboard states, rather than events. I've hacked support for buttons into these commands, but their state is reset after every frame. Multiple tap support is risky because instead of counting the number of events, I have to rely on the game engine to poll during the right times. At 60hz, that basically should be fine, but in some of the bigger battles, my phone at least slows down to about 5 to 10 hz. 

I like the related suggestions from upstream. I'm thinking one of the following: 
1. Add support for touch events to the buttons, including key-up and key-down, and modify the command injection logic to retain state until the key-up event. This I think would end up looking more like what veteran PC players would expect. 
2. Add a config value for a "fleet jump", which would automatically wait until the entire fleet is ready. This would involve tinkering with the autopilot ai code, which is kind of brittle. I think this would work out closer for what new players would expect, and is easier for players with touchscreens.

**Comment by asl97** [comment]
How many people actually need native touch support?  Sure it's nice but a simple customizable overlay would do just as well.

Something like ppsspp button overlay but better (such as layout actually matching what is shown instead of being slightly off).

Bonus is it would work without needing to modify the upstream source much, just how it handle inputs

https://github.com/thewierdnut/endless-mobile/issues/14#issuecomment-1311698965
thewierdnut commented:
> I have modified a few of these ui's, but they have a nasty habit of being changed upstream

And it helps with other issues like #12 #21 and any others that isn't implemented yet.

Since this is not the first of such projects(porting game to android), I tried searching for library that can help add an overlay and end up finding something call "GP Overlay" in my search and tried it out and it works surprisingly well for a quick jump test, not sure how trustworthy the app is though.

Speedup 2x:

https://user-images.githubusercontent.com/4752645/205505866-6b39fb26-dc83-4cd9-8f32-8ff7d7bed7a0.mp4

**Comment by johndh** [comment]
This would also solve #15 , would it not? It seems most of the issues specific to this project are issues of translating keyboard-based controls to a touchscreen.

**Comment by thewierdnut** [comment]
I would love to try out this overlay, but I must admit, I am extremely skeptical. Other ports that just slap an overlay on top of the game have always come off as extremely awkward to me. (Like Meritous, SuperTuxCart, most game console emulators, etc). The reality is that fast-paced button-based gameplay does not translate well to a touchscreen interface. The converse can also be true. Most stylus-based games for the DS are awkward to play on the PC, but work great in android, given the appropriate emulators. 

Most games that make the transition from desktop to mobile have to make certain gameplay changes in order to make the transition more smooth. A good example is Mindustry, which on mobile versions allows you to pause and scroll the map, your ship auto-fires and/or heals buildings automatically, and has a separate command mode, none of which exists on the desktop version. 

Endless sky probably lies in the middle of the spectrum. It relies a lot on keyboard controls, but it also has a lot of mouse controls as well. It has a lot of fast-paced battles, but also some slower story-telling. For the most part, the port went rather smoothly. I was able to play through huge portions of the game just by adding touch navigation and a jump button (and buying some fighters to escort me). However, fine grained control of flight and fleets will always be inferior on a touchscreen interface, as there are just too many commands you can give. 

People will adjust their playing style to fit the touchscreen controls, which for me meant less focus on one-on-one combat, and more focus on heavily armed escorts. I would like to make other playing styles practical though, which means adapting to the touchscreen whenever possible. In a lot of cases, this means allowing the AI to make many decisions for you, such as when to fire, and when to jump. These types of changes will unfortunately mean more intrusive changes to the upstream code, but I think it makes for much better gameplay.

**Comment by johndh** [comment]
> A good example is Mindustry, which on mobile versions allows you to pause and scroll the map, your ship auto-fires and/or heals buildings automatically, and has a separate command mode, none of which exists on the desktop version.
> 
> However, fine grained control of flight and fleets will always be inferior on a touchscreen interface, as there are just too many commands you can give.

I had already been thinking that the ability to pause and scroll the map would be a huge benefit to the RTS experience that ES kinda already has, but especially on a touchscreen. I think that could also make the problem of too many buttons, less of a problem if a lot of them are only shown when paused.

Much like Mindustry, the flagship is basically your cursor, but in ES the view is too small and the ship too slow for this to work well.

Related issue that was closed for being an overt knockoff:
https://github.com/endless-sky/endless-sky/issues/6523

**Comment by johndh** [comment]
Is this expected to work with the new secondary fire buttons? https://github.com/endless-sky/endless-sky/pull/6877

**Comment by thewierdnut** [comment]
It should, yes
