### ISSUE TITLE
I need help making the secodary fire buttons on the bottom left

### ISSUE THREAD

**Issue by ty1221pro** [thewierdnut/endless-mobile#31]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I need help making the secondary fire button to the left since I'm not left handed and I use my right hand for engine steering

### Steps to Reproduce

Can't figure out how to change it

### Expected Behavior

Needs to change

### Device type

Galaxy s9+

### Game Version

0.9.16-1

**Comment by thewierdnut** [comment]
Those icons are positioned via interfaces.txt, so it wouldn't be too hard to make a plugin for that. You just need to adjust the "ammo unselected"/"ammo icon" elements and their related buttons in the interfaces.txt. Visually, it would cover your fleet icons, but presumably you would be ok with that. 

The input handling is another problem though. The interface uses mouse events, which SDL interprets as a single touch point on the screen. There isn't the plumbing necessary that makes it so that you can fly with one finger while another finger is pushing buttons.

Issue #22 describes a solution using an overlay instead, which would simulate keyboard presses. I haven't looked at that solution yet, but it could potentially work here as well.
