### ISSUE TITLE
Support for game controllers

### ISSUE THREAD

**Issue by Karirawri** [thewierdnut/endless-mobile#32]
### Problem Description

I got myself a bluetooth controller and i want to use it in the game, but it's not properly recognized. one button is recognized as "return" and can be mapped, but the rest is dead. My specific controller is a bootleg one that is recognized as a ps4 controller on other games like terraria and the retroarch emulator.

### Related Issue Links

none

### Desired Solution

Controllers need to be recognized and able to be properly mapped to on the settings. Optionally, when analog is available, movement with it could be truly analog if possible.
Navigating the UI could be done either by selecting with the d-pad and confirming with one of the buttons or by having a specific button for each thing (like, X to launch, O for spaceport, etc.)
Long UI things that can be scrolled through, like the outfitter, could be scrolled through using the right analog or shoulder buttons.
Essentially, touchscreen input could be reserved for the more complex parts where it's inevitable.

### Alternative Approaches

If controlling parts of the UI with the controller is not possible, merely being able to map the keys in the settings to controller buttons should suffice.

**Comment by thewierdnut** [comment]
This shouldn't be too difficult, but I might wait a bit due to some of the upstream integration being worked on. 

See upstream issue https://github.com/endless-sky/endless-sky/issues/3972 and in progress pull request https://github.com/endless-sky/endless-sky/pull/7132

**Comment by thewierdnut** [comment]
The latest continuous build should now have some basic controller support. You can set your controller preferences, plus configure a new game controller if SDL doesn't recognize it correctly. Many of the dialogs also work, although you still still have to use a keyboard for text input. The main flight screen should allow you to fly around, shoot things, and jump from system to system. 

I'm still leaving this issue open because I need to go though the various dialogs and panels and add joystick navigation.
