### ISSUE TITLE
APK update size quite large

### ISSUE THREAD

**Issue by asl97** [thewierdnut/endless-mobile#53]
### Problem Description

It's probably fine if it's a standalone APK, but updating the game using fdroid, uses quite a bit of data and downloading from fdroid is quite slow.

### Related Issue Links

https://f-droid.org/en/2017/02/20/f-droid-supports-apk-expansion-files-aka-obb.html

### Desired Solution

I am not too sure on the specific on the options are available

OBB, AAB, seperate base apk, some kind of custom resources manager.

### Alternative Approaches

Continue as usual?

Use github page as a fdroid repo server?

### Additional Context

I ain't sure how easy it be to separate resources from apps but it may be worth looking into.

**Comment by thewierdnut** [comment]
The upstream port has 228 MB of graphics installed with the base game. There is a plugin system that will install even more. 

Most of the time there are updates, they are to the game data, and not to the base app, and so the full set of resources would have to be re-installed anyways. 

I am working on texture compression, which should save quite a bit of space in both the apk and the runtime memory use, but its still to early to guess how much it would help.

**Comment by asl97** [comment]
> Most of the time there are updates, they are to the game data ... full set of resources would have to be re-installed anyways.

the game data is mostly just text file and graphics

for the first time a full download would be require consisting of the main OBB and the patch OBB, which contain any update since the main OBB creation.

Ideally the main OBB doesn't change until upstream decide to refresh basically everything again or if the patch OBB get quite large

While this method isn't as optimum as `git pull; make` on linux nor whatever method modern app on the play store is doing for delta patching, it should be better than a full download everytime

The main drawback being the apk would no longer be standalone and might require an additional download step on startup.

**Comment by thewierdnut** [comment]
I am new to both android and java development, so this is not a process that I am familiar with. That being said the resources for developing and using OBBs seem to be documented here: 

https://developer.android.com/google/play/expansion-files.html
https://f-droid.org/en/2017/02/20/f-droid-supports-apk-expansion-files-aka-obb.html

There seem to be some upshots to the OBB file scheme:
1. Minor updates can be sent via small "patch" files. 
2. Code updates for the main app can be sent without modifying the data

They come with downsides though:
1. OBB files requires direct support within the java-side code. 
2. Depending on the android version, extra permissions may need to be required.
3. A developer would have to track each delta, deciding what type of update is required (main app, OBB, patch OBB)
4. The app is dependent on communicating with f-droid/google play for OBB downloads, and can no longer be built or installed independently. 

An alternative may be to download resources directly from gitlab, but a lot of development would be needed to achieve feature parity with the OBB files. 

I'm going to leave this issue open in case I find time to investigate this further in the future, but it does not look like a near term possibility.

**Comment by asl97** [comment]
> The app is dependent on communicating with f-droid/google play for OBB downloads, and can no longer be built or installed independently.

Technically you can still install it manually, just download and put the obb files in the right spot and it works, it just troublesome and with the recent 'safety' feature from accessing `android/data`, it's a pain.

It's common knowledge to anyone who know the android piracy scene.

> An alternative may be to download resources directly from gitlab, but a lot of development would be needed to achieve feature parity with the OBB files.

If you mean bundling git and having very good delta updates, I would totally love that, we technical don't need feature parity with OBB files

Just a way of separating static media and data from program.
```bash
if no data do
   git clone
else
   if "$(git show  --format="%h" --no-patch)" == commit do
      exit 0
   done
done

git fetch
git checkout commit
```

Drawback being requiring internet on first launch on install/update.

There are probably other ways of doing it like resource apk, example being hacker keyboard's plugin system of dictionary, no idea if it's an official api or if it's something specific to hacker keyboard.

The resource apk contain the base directory and the main apk has an overlay directory and it basically works like an `Overlay filesystem`
____

This is definitely not a near term thing, the only near term solution to this is maybe defaulting to a half res texture pack which should quarter the size

Kind of like how the pc version has the 2x HD pack, android could have a 2x PC Res (default) pack

**Comment by thewierdnut** [comment]
The 2x HD pack has some hacks in place. It reads the original file first to determine the *intended* texture size so that it knows how big to render the texture. It then load the larger texture size instead. 

Likewise, "Reduced graphics" mode will read the original image size, and then cut the width and height in half. Both solutions require the original graphics to be present, and having a "Half resolution" pack of some kind would need a way to communicate the render width and height as well as the actual image size. 

An alternative solution that I have been testing is to use texture compression, which should cut down on both the apk size and the runtime memory requirements. Stay tuned :D

**Comment by asl97** [comment]
> Both solutions require the original graphics to be present, and having a "Half resolution" pack of some kind would need a way to communicate the render width and height as well as the actual image size.

That sound very hacky but easy to workaround with another hacky solution, assuming I ain't missing something, create dummy indexed PNG with the right size but basically is a transparent or 1 color PNG which will be very small.

Here a dummy 255x255 at just 229b or 0.23kb:
https://user-images.githubusercontent.com/4752645/223396755-0461cf1e-dccb-46b8-a1f9-d00e66fccd3a.png


> I have been testing is to use texture compression

has the results been good?  as far as I am aware of, PNG is already pretty compress and short of converting to indexed or a different format, it shouldn't reduce it by much apk wise, as for memory usage, I doubt that more since it should be decoded raw image data in the game engine which should remain similarly sized

**Comment by thewierdnut** [comment]
The 2x HD pack has a special tag on each filename that causes it to load both versions in memory. I don't like that solution as it is memory intensive and requires special handling in the image buffer code. Any changes I make there will be fragile and prone to breaking when I rebase on the upstream code. 

Texture compression is slightly different than image compression, in that it is designed to be used and read directly from the device memory in compressed form, without needing to be decompressed first. This is different than png or jpeg, which are storage-only formats that need to be completely decompressed in order to be used. The texture compression I am using is ETC2. I picked it because it is a mandatory part of gles3, which endless-sky uses. Unlike png, it is a lossy format, but I haven't noticed any compression artifacts so far. I would love a second opinion on other devices though. 

ETC2 compression, even though it is lossy, only manages png-like levels of compression if an alpha channel is required. With no alpha channel, it gets closer to jpeg-like levels of compression. Since it is a fixed-ratio compression technique though, the DEFLATE algorithm used by zip (and thus apk) actually manages to compress it down even further, which shrinks the apk size from 260 MB to 145MB. This is a significant savings, but short of my goal of 100 MB. 

As a bonus, the runtime memory requirements on my device drop from 1200MB to 600MB, which is enough that my device can handle the game again without reverting to reduced graphics mode. So far, I'm not noticing any compression artifacts and the gameplay is smooth, though I would love to get a second opinion from other devices. 

I think that in order to achieve my goal of a 100MB apk, I will have to reduce the size of many of the textures. Since I am using the ktx file format to store them, I can put in extra metadata to indicate the intended texture size as well as the actual texture size, which would remove the need for any hacks involving the original textures.  A stretch goal would be to convert all of the wav sound effects to mp3, which should save me an additional 30MB or so. It should be easy enough at that point to make some plugins containing the original or even the 2x HD content that the user can install after the fact.

**Comment by asl97** [comment]
I did a dumb thing and it got me [134 MB](https://github.com/asl97/endless-sky/actions/runs/4363357661) without touching the jpg which seem to be the last bunk of the size

https://github.com/asl97/endless-sky/blob/0e9d3bc9635ae4fe01c9afa785b8daa87f2f0879/Indexed%20Image%20Patch.py#L16-L27

![image](https://user-images.githubusercontent.com/4752645/223708557-fdaca8fc-a256-4b35-a36b-ab83b65fe969.png)

The sound file using wav is probably a low hanging fruit, I ain't sure about using mp3, there are newer and less 'patent' nonsense format out there like ogg, I guess whatever you use just depends on whatever endless-sky uses support

With both, getting the apk down to under 100MB should be possible

Assuming I did the profiling thing to record memory usage correctly, it seem to be using 1.5gb?
![image](https://user-images.githubusercontent.com/4752645/223708017-f309f6aa-0614-4ce3-ad11-b7c1dcc8ab81.png)

With the setting reduced graphics mode, it drop to 0.8gb

Ideally fdroid should just support delta updates, even google play has it since long ago, but there doesn't seem to be much progress on it:
https://gitlab.com/fdroid/fdroidclient/-/issues/450
https://gitlab.com/fdroid/fdroidserver/-/issues/18

____
Once there is an apk, I can probably test it on my device.

**Comment by thewierdnut** [comment]
I've tried the indexed PNG thing before. The UI components ended up visibly dithered, and many of the textures had large blocks of incorrect colors. I don't know if that was a problem with the compressor or the decompressor, but I ended up abandoning that approach. It could probably still be made to work though. 

Indexed png files do not help with runtime memory requirements. On endless-mobile, reduced graphics mode will drop half of all animation frames, and reduce the size of larger textures to under 500x500 pixels. This makes many of the larger sprites appear blurry. The compressed textures give us the runtime memory reduction without sacrificing the resolution. 

The only reason I bring up mp3 is because the game already has support for it via a dependency on mad. If the [wikipedia page](https://en.wikipedia.org/wiki/MP3#Licensing,_ownership,_and_legislation) is accurate though, the "patent nonsense" should have all expired in 2017 in the united states, and earlier in the rest of the world.

**Comment by asl97** [comment]
> I don't know if that was a problem with the compressor or the decompressor

The issue is because indexed is limited to 256 colors at most, a simple gradient will easily use up all the available color slots, or even just resizing a image can easily increase the amount colors, to be pixel perfect, the graphic has to be designed and created to size to work perfectly with indexed.

It's not really practical to manually go through the process for all 5063 png and jpg with it's lossy is just not suitable to be automatically converted to indexed.

the python script I have created as a test could be amended to include a check using `PIL.Image.Image.getcolors` to count the number of colors and if it's less than 256, it should be able to convert losslessly to indexed for those that are suitable

> compressed textures give us the runtime memory reduction without sacrificing the resolution.

Honestly it sound like a fairly invasive change, I clearly do not know enough of endless sky internal to say anything definite right now,  but if there any plan on upstreaming it,  it should be good

> I bring up mp3 is because the game already has support for it via a dependency on mad.

I am surprise, they added it before the patent expired,  in any case,  almost everyone agree that there are better format than mp3,  if it's hard to do it with other format, I guess it will do for now

**Comment by thewierdnut** [comment]
> > I don't know if that was a problem with the compressor or the decompressor
> 
> The issue is because indexed is limited to 256 colors at most, a simple gradient will easily use up all the available color slots, or even just resizing a image can easily increase the amount colors, to be pixel perfect, the graphic has to be designed and created to size to work perfectly with indexed.

The gradients were why the UI components were dithered, but the large blocks of incorrect colors (I'm talking bright purple instead of dark gray or black) were obviously bugs. 

The dithering was actually unnoticeable for all the non-ui sprites through. Other than the buggy blocks of color that seemed to affect one out of every 10 outfits or so, I was pleased with the results

> Honestly it sound like a fairly invasive change, I clearly do not know enough of endless sky internal to say anything definite right now, but if there any plan on upstreaming it, it should be good

It is, and it isn't. I basically need to wrap every `glTexImage3D` call in a conditional statement that calls `glCompressedTexImage3D` for compressed textures. 

I've been chatting with developers on the discord, and there doesn't seem to be any objection to it. I'll try for a merge request later this week I think.

**Comment by asl97** [comment]
> but the large blocks of incorrect colors (I'm talking bright purple instead of dark gray or black) were obviously bugs.

Sound like you might be using a fixed palette and it's using the closest color to what it suppose to be or the software is not using the embedded palette or something else

From the answer from stackoverflow, my python script is probably not doing the right thing.

https://stackoverflow.com/a/74916759

A lot of software do just default to web palette


> I've been chatting with developers on the discord, and there doesn't seem to be any objection to it. I'll try for a merge request later this week I think.

So you be adding support for a new format, ktx

And I guess it might be hard to push for a upstream change from png/jpg to ktx, but that should be simple enough to add to the CI that builts the apk, it will probably increase build time by a minute or two.

**Comment by thewierdnut** [comment]
> And I guess it might be hard to push for a upstream change from png/jpg to ktx, but that should be simple enough to add to the CI that builts the apk, it will probably increase build time by a minute or two.

I won't be adding automatic texture compression to the CI. It takes several hours to run. Instead, I'll manually maintain the textures in the android assets directory, and probably add a build step to notify me if the source images have changed. The images/ folder that I source those from will remain untouched.

**Comment by thewierdnut** [comment]
I added some metadata to the ktx files that specified the intended texture size, and then downsized all the planet images (and some other large textures as well), which got me close to the 100MB target. 

Give it a try and tell me what you think. 

https://github.com/thewierdnut/endless-mobile/actions/runs/4385944598

**Comment by thewierdnut** [comment]
Added mp3 support, and compressing all the audio pushes the size down to 70 MB, well below the 100MB target. 

If somebody could give me some feedback on whether it is working or not, that would be great. Otherwise I'll just close this and cut a new f-droid release in a week or so. 

https://github.com/thewierdnut/endless-mobile/actions/runs/4463161739

**Comment by zuckung** [comment]
70 mb  version works good, although the 107 mb version started twice as fast. Anyway, both are great improvements. Thanks

**Comment by thewierdnut** [comment]
> the 107 mb version started twice as fast.

I believe it. the 70mb version has to decompress all of the audio, where the 107 mb version had it all stored decompressed already. 

I have other ideas that I'm hoping will affect the startup speed.

**Comment by thewierdnut** [comment]
Fixed by a846dd335c641ad92efaeed1dc21cafee467642f

**Comment by asl97** [comment]
Any guide to generating those ktx files?  Possibly for when packing plugins for mobile.
____
> I've been chatting with developers on the discord, and there doesn't seem to be any objection to it. I'll try for a merge request later this week I think.

Btw, whatever happened to upstreaming it anyway?  No discussion on ktx seem to have happened on upstream github repo and no sign of ktx in code either.

**Comment by thewierdnut** [comment]
> Any guide to generating those ktx files? Possibly for when packing plugins for mobile.

No guide. I probably should write one, but the process is simple for linux users, and hard for everybody else. 

I created a separate project using the defunct etc2comp library at `android/app/jni/src/texture_tool`. It does a lot of things with the images, including premultipliying them, placing some tags in the ktx file indicating the original file size and checksum, and combining animation frames into a large multi-texture.

The tool also has a batch mode, which can recursively parse through all images in a folder, recompressing all images it finds to a new target directory structure. I've tested it on plugins and it works fine. I run the tool with the arguments `texture_tool --reduce 2 --batch images/ --output android/app/src/main/assets/endless-sky-data/images/`. It takes about six hours to run through the initial batch of endless-sky textures, but if the ktx file already exists, it will compare the stored checksum in the ktx metadata against the source file and skip it if it hasn't changed. 

> Btw, whatever happened to upstreaming it anyway? No discussion on ktx seem to have happened on upstream github repo and no sign of ktx in code either.

KTX is just a container format that supports any texture compression type. For mobile, I'm using ETC2 compression, which is a defunct format. 

ETC2 was included as a requirement for gles3, but *not* for opengl 4 (the equivalent desktop format). Only mobile chipsets support ETC2 in hardware, with desktop implementations that claim to support gles3 decompressing the texture in software before uploading it to the card. There hasn't been much appetite to support it on desktop.

Since KTX just stores the opengl texture compression constant, and then the texture information itself as a binary blurb, I suppose we could support just about any texture compression format, including the ones supported by desktop cards with a single implementation, except there are two complications. The first is that the png/jpg (and soon avif) formats are well standardized and easy to modify, which is part of the strength of the game. People love to take the default game assets, and change them around to make plugins. The second is that as part of the game loading sequence, the game sprite information is loaded and the alpha channel processed in software to make collision masks. I have re-implemented the alpha channel loading of ktx in software to support this, but this would need to be done for any new texture format supported. The alternative would be to separate the collision information into separate data files somewhere, which would make editing the game even more complicated. 

Given that the game loads in a reasonable time already, and most desktop implementations don't have the same space constraints that an android implementation does, I don't think there will ever be an appetite for texture compression on the desktop.

**Comment by asl97** [comment]
> Given that the game loads in a reasonable time already, and most desktop implementations don't have the same space constraints that an android implementation does, I don't think there will ever be an appetite for texture compression on the desktop.

I am looking at it from a compatibility point of view, if plugin starts offering mobile optimized version, there might be low-end pc users who just thought to try the mobile optimized version only for it to not be able to load.

But I guess it's too early to worry about that for now, people can just do their own thing for now and just put a note stating that the pc version doesn't support the mobile optimized plugin (re)pack, and to just download the normal version.
