### ISSUE TITLE
Point to F-Droid the languages available in the app

### ISSUE THREAD

**Issue by Korb** [thewierdnut/endless-mobile#54]
### Problem Description

The F-Droid mobile app currently has the ability to display app descriptions in OS language. However, as I noticed, regardless of the installed Google Android interface language, the description of Endless Sky is displayed only in English or in ruzzian. From this we can assume the app is only available in those two languages. But it doesn't say so directly in the description. To check this, you have to install the application, run it, and only by the absence of the corresponding choice in the main menu make sure that - yes, there is no language choice. Or, the user's preferred language is not in the available list of languages.

### Related Issue Links

https://f-droid.org/en/packages/com.github.thewierdnut.endless_mobile/
https://f-droid.org/de/packages/com.github.thewierdnut.endless_mobile/
https://f-droid.org/es/packages/com.github.thewierdnut.endless_mobile/
https://f-droid.org/fr/packages/com.github.thewierdnut.endless_mobile/

### Desired Solution

The description of the application in the repositories corresponds to the language selected by the user, and this description lists the languages supported by the application.

### Alternative Approaches

![Screenshot_20230305_163222](https://user-images.githubusercontent.com/3509797/222963577-b46b34c6-8acb-4370-9941-cf50c30c1794.jpg)

**Comment by thewierdnut** [comment]
I'm not sure what you are asking for. 

The upstream code base has many user-displayed strings embedded directly into the code, and the fonts are all pre-rendered English only characters. The descriptions in the metadata provided to f-droid are all tagged as en-US, and I am unaware of any "ruzzian" descriptions as part of the package. 

There is some effort to provide internationalization support in the upstream project. see https://github.com/endless-sky/endless-sky/issues/558

**Comment by Korb** [comment]
I understand that the game currently only fully supports English. It's a pity. This is exactly what I expected to see in the description of the game in its description on F-Droid.

Will the article "[Translation and Localization](https://f-droid.org/en/docs/Translation_and_Localization/)" and "All About Descriptions, Graphics, and Screenshots" / "[Fastlane structure](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#fastlane-structure)" help clarify the situation with localized descriptions?

**Comment by thewierdnut** [comment]
Just curious... what languages do you understand? 

I've already had to change a lot of code to get the current font renderer to work with compressed textures. If I switched to a unicode font renderer, it should be possible to create a plugin that has all of its dialogue translated to a new language. That wouldn't help with button labels and other pre-rendered text, but it would be a good first step. I would need people willing to do the translation though.

**Comment by Korb** [comment]
> what languages do you understand?

Russian, a little Ukrainian and French.

**Comment by thewierdnut** [comment]
Ok. We've wandered a little far away from the original intent of the post, which was to somehow indicate that English was the only supported language for this app. 

In the metadata, it already lists en-US as the only language supported, but f-droid will use en-US as the fallback if the native language is not listed, which is probably the source of the confusion. In the meantime, I've added some text to the description as requested to indicate that english is the only currently supported language. That text will not show up on f-droid until I push a new version, which may be several weeks. In the meantime, this issue will auto-close once I push the new comments to github. 

In the meantime, I would love to add support for new languages, but I will need help as I only speak English. The easy part will be adding unicode support to the font renderer. The hard part will translating all of the dialogue in the data directory, which is going to be a huge initial effort, followed by a commitment to keep up with new changes as new versions are released. 

If anybody is willing to maintain a translation, please respond here with the indicated language. Overlap in languages is great, because then you can check each other's work. If there is interest, I can get started on the unicode support, and add language-specific github issues to track progress. As a base, I believe there are some language-specific forks of endless sky, whose data directories could serve as a starting point for translation. 

Thank you in advance for any help you are willing to offer.
