### ISSUE TITLE
Open a pull request for mobile support upstream?

### ISSUE THREAD

**Issue by samrocketman** [thewierdnut/endless-mobile#55]
Any plans to open a pull request upstream to ES for building the mobile version?

Adding on what's available for packaging I think would be great.

**Comment by thewierdnut** [comment]
I tried that already, and was shot down. That is why I created this fork instead. 

https://github.com/endless-sky/endless-sky/pull/6689

**Comment by thewierdnut** [comment]
Actually, let me ask a slightly different question...
Are you referring to mobile support? Or to the number of patches I have made that also work on the desktop build? 

I've made a number of ui and interface updates in order to support mouse/touchscreen controls that would probably be accepted upstream. I'll go through them and see what would be useful.

**Comment by samrocketman** [comment]
If possible a bit of both.  I think it would be cool if multi-device support became a reality.

If GitHub actions generated an apk my fork would also be able to.

**Comment by off-by-zero-error** [comment]
touch interfaces on desktop increase accessibility, and they look cool when they actually work.  i don't see why upstream wouldn't accept more input methods, especially since it's not tying them to an extra release.  +1 for picking updates for upstream, for the good of the galaxy!
