### ISSUE TITLE
Jump button not responding

### ISSUE THREAD

**Issue by Thunderhurst** [thewierdnut/endless-mobile#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After the update to 0.10, the Jump button is no longer responding to taps. My phone screen is curved, but the Menu button just next to it still functions.

### Steps to Reproduce

1. Enter ship
2. Depart the port
3. Tap Jump button

### Expected Behavior

Autopilot engages, after steering, the ship hyperspace jumps

### Device type

OnePlus 7 Pro

### Game Version

0.10.0-31

### Additional Information

Might be a bug in the compact layout plugin? I haven't test v0.10 on a PC yet.

**Comment by thewierdnut** [comment]
Can still steer? 
Does the map button work? 
Do you have plugins installed?

**Comment by thewierdnut** [comment]
> Might be a bug in the compact layout plugin? I haven't test v0.10 on a PC yet.

Compact layout plugin just moves the planet image into the background of the content window so that you can zoom in further. It doesn't do anything with the main buttons.

**Comment by Thunderhurst** [comment]
Steering - Yes
Map button - Yes
Plugins - only Compact layout

And good to know about the compact layout plugin, thank you!

**Comment by Thunderhurst** [comment]
Upon further troubleshooting, I found that I can tap the Jump button, but it is an extremely small hitbox, usually taking upwards of 20 taps to get right.
I also confirmed this issue does not occur on 0.9.16.1-30 after a downgrade.

**Comment by thewierdnut** [comment]
what happens if you hold down the jump button for a second instead of trying to tap it?

**Comment by thewierdnut** [comment]
I'm curious... what kind of framerates are you getting in this game? What is your cpu load? You can check the CPU load at least by turning on Preferences->Settings->Show CPU/GPU

**Comment by thewierdnut** [comment]
Also, can you export and attach your save file?

**Comment by Thunderhurst** [comment]
Whelp, I should have thought of that. Pressing and holding for a second or two has triggered the Jump button every time so far. That was definitely a user error on my part. 
Was this mentioned in the release notes? I thought I read them, but could've easily missed it.
Also, I'm such a newbie I didn't realize you could export your save file, and lost mine on downgrade. Guess I learned the hard way!
Thank you for the help!

**Comment by thewierdnut** [comment]
Rather than using an event driven approach, endless-sky scans the state of the keyboard on each frame. This mechanism has been hooked for the android port, and it makes it very possible to click on an input and then release it in between frames if your device is having a hard time keeping up. That is why I asked you for your CPU/GPU usage. 

I suspect that holding down the jump button longer makes it more likely that the per-frame engine logic notices that you are pushing it, even if your device is running slow. 

I'm going to leave this issue open for now, because I want to adjust the button hooks to the command system so that the command stays active for at least one frame, regardless of how long you push it .

**Comment by Thunderhurst** [comment]
Understood. While playing, I've seen my CPU usage typically hovering between 6%-13%, never above that. My GPU usage seems to be stuck at 15% nearly all of the time.
