### ISSUE TITLE
Can't get keyboard to appear on text boxes

### ISSUE THREAD

**Issue by markasoftware** [thewierdnut/endless-mobile#8]
When I tap the textboxes where you're supposed to enter your name, no keyboard appears. I'm running lineage 19 and using endless sky from f droid

**Comment by thewierdnut** [comment]
I've noticed that it doesn't appear by default when you click on the first
name, because the first name already has the focus, but clicking on the
second name always brings it up for me. As a work around, you should be
able to turn on permanent notifications in your keyboard settings, which
allows you to bring up the keyboard at any time.

I'll take a look at the keyboard issue this weekend.

**Comment by markasoftware** [comment]
Alright, it works when I tap the text box. I was just using the "OK" button to switch fields before which wasn't good enough

**Comment by thewierdnut** [comment]
"OK" button? What type of phone do you have?

**Comment by markasoftware** [comment]
Just the "ok" button that's in the game right next to the text boxes, it automatically switches between the text fields.

**Comment by thewierdnut** [comment]
This should be fixed now for build 29
