### ISSUE TITLE
Option for disabling "click for move"

### ISSUE THREAD

**Issue by genry718** [thewierdnut/endless-mobile#80]
### Problem Description

New joy and new gestures are awesome but when you start to drawing gesture ofc mainly it works like click and u changing direction. If this approach can be customized without major changes - how about option for this?

But "click for taget" and "click for board/land" tare useful with joy too, dont want to broke them.

### Related Issue Links

no

### Desired Solution

maybe option?

### Alternative Approaches

antire disabling interaction but its not good

**Comment by thewierdnut** [comment]
The problem is that I don't know if the user is just dragging their finger to guide the ship, or if they are attempting to draw a gesture until after they lift their finger back off the screen. 

What if I disable click-to-move entirely if the on-screen joystick is in use? all the other stuff (clicking on targets, planets, etc) would still work.

**Comment by YiffLord** [comment]
> The problem is that I don't know if the user is just dragging their finger to guide the ship, or if they are attempting to draw a gesture until after they lift their finger back off the screen.
> 
> What if I disable click-to-move entirely if the on-screen joystick is in use? all the other stuff (clicking on targets, planets, etc) would still work.

Seems like a very nice solution. Tho not all users use Joystick. I personally don't like using a Joystick.

**Comment by genry718** [comment]
yes, maybe i'm bad in explonation, that what i want
