### ISSUE TITLE
Non responsive UI

### ISSUE THREAD

**Issue by YiffLord** [thewierdnut/endless-mobile#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The UI does not respond when selecting ships in the shipyard menu. Upon tapping a different ship icon the action will often be ignored, as if you never tapped. This is especially common when attempting to select another ship after having already selected one.

### Steps to Reproduce

1. Go to shipyard menu.
2. Tap on any ship icon.
3. Repeat and observe that it is a fairly common occurence. 
4. Unprofit.

(thewierdnut, note to self:)
Brokenness 1:
1. Go to the shipyard screen
2. Select more than one of "Your Ships:" on the right side of the screen. 
3. Select a ship for sale on the left side of the screen. Note that the set of selected ships is not preserved. 

Brokenness 2:
1. Go to the shipyard screen
2. Select one or more of "Your Ships:" on the right side of the screen.
3. double-tap on one of the ships for sale on the left side of the screen. Note that all ships on the right are deselected.

(YiffLord additional issue:)                                       [Delete if no issues found]
1. Go to the shipyard screen.
2. Select one or more of "Your Ships:" on the right side of the screen.
3. Double-tap a ship for sale/tap with rather quick succession multiple ships for sale.
4. Note that in addition to deselecting "Your Ships:", the selection of ships for sale becomes stuck/unresponsive, preventing the user from selecting other ships for sale for a certain period of time.

### Expected Behavior

The action should be processed. 

(thewierdnut, note to self:)
The selection logic on the for-sale (left side) and "Your Ships:" (right side) should not affect each other. 

### Screenshots

/

### Link to save file

/

### Device type

Overclocked Samsung Tab S2 9.7 Black

### Game Version

Latest continuous as of the 23rd of July 2023.

### Additional Information

It is not game breaking, but it's amazing how such a small error can be so infuriating. 
Thanks for your efforts btw.

**Comment by thewierdnut** [comment]
I've seen some complaints on discord about the selection being "sticky". I'm not seeing any unexpected behavior, but maybe I'm biased because I know what to expect. 

I'm assuming you are talking about the ship selection area here:
![image](https://github.com/thewierdnut/endless-mobile/assets/9004013/b9c01666-803d-4e5f-b5e1-5000cd64c466)

I've implemented three custom behaviors here: 

1) A double-tap will select all contiguous ships the same type as the one double-tapped, unselecting all other ships.
2) A long tap  will select or unselect the the tapped ship.
3) Tapping a ship when it is the only ship selected should unselect it (ie no ships will be selected)

Upstream behavior that should still work:
1) Tapping a single ship (when it isn't already the only selected ship) should select that ship, deselecting all others. 
2) Dragging and dropping to rearrange ships. 

Will you let me know what specific behavior is broken?

**Comment by YiffLord** [comment]
No, I was talking about the purchase ship selection, not your existing fleet.

I haven't had any issues with the fleet selection UI, it seems to work accordingly, atleast on my behalf.

**Comment by YiffLord** [comment]
Ok I think I found the problem, it has to do with the existing ship selection UI behaviour, which works accordingly but overboard. I don't know how to explain this in a compact way so I suggest a DM on Discord for easier communication. 
Username: lostyposty
